package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"fmt"
	"strings"

	"github.com/99designs/gqlgen/graphql"
	"github.com/e-mbrown/rollWOD/graph/model"
)

// Characteristics is the resolver for the characteristics field.
func (r *queryResolver) Characteristics(ctx context.Context) ([]*model.Characteristic, error) {
	allChar := []*model.Characteristic{}
	for _, v := range r.characteristics {
		allChar = append(allChar, v)
	}
	return allChar, nil
}

// Titles is the resolver for the titles field.
func (r *queryResolver) Titles(ctx context.Context) ([]*model.Title, error) {
	allT := []*model.Title{}
	for _, v := range r.titles {
		allT = append(allT, v)
	}
	return allT, nil
}

// Sects is the resolver for the sects field.
func (r *queryResolver) Sects(ctx context.Context) ([]*model.Sect, error) {
	allSects := []*model.Sect{}
	for _, v := range r.sects {
		allSects = append(allSects, v)
	}
	return allSects, nil
}

// Traditions is the resolver for the traditions field.
func (r *queryResolver) Traditions(ctx context.Context) ([]*model.Tradition, error) {
	return r.traditions, nil
}

// GetSect is the resolver for the getSect field.
func (r *queryResolver) GetSect(ctx context.Context, name []string) ([]*model.Sect, error) {
	res := []*model.Sect{}

	for _, v := range name {
		n := strings.ToLower(v)
		val, ok := r.sects[n]
		if ok {
			res = append(res, val)
		} else {
			fmt.Print(n)
			graphql.AddErrorf(ctx, "Non-fatal error: parameter '%s' is not a sect", n)
		}
	}

	if len(res) == 0 {
		return nil, graphql.GetErrors(ctx)
	}

	return res, nil
}

// GetTradition is the resolver for the getTradition field.
func (r *queryResolver) GetTradition(ctx context.Context, name string) (*model.Tradition, error) {
	panic(fmt.Errorf("not implemented: GetTradition - getTradition"))
}

// GenInfoByName is the resolver for the GenInfoByName field.
func (r *queryResolver) GenInfoByName(ctx context.Context, name string) (*model.GeneralInfo, error) {
	res, ok := r.genInfo[strings.ToLower(name)]
	if !ok {
		return nil, fmt.Errorf("%s: is not a entry in the conpendium", name)
	}
	return res, nil
}

// GenByID is the resolver for the GenByID field.
func (r *queryResolver) GenByID(ctx context.Context, id string) (*model.GeneralInfo, error) {
	panic(fmt.Errorf("not implemented: GenByID - GenByID"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
